// Downloads the typefaces the original FOSCO theme used and self-hosts them, so the
// site keeps its typography with no external requests (and no CSP exemption).
// All three are open-source: Public Sans (OFL), Red Hat Display (OFL), Rajdhani (OFL).
// Usage: node scripts/fetch-fonts.mjs
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const OUT = path.join(process.cwd(), 'client', 'public', 'fonts');
// A modern UA makes the Google Fonts API serve woff2 rather than ttf.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Public Sans', css: 'Public+Sans:wght@400;600;700', slug: 'public-sans' },
  { name: 'Red Hat Display', css: 'Red+Hat+Display:wght@700;800', slug: 'red-hat-display' },
  { name: 'Rajdhani', css: 'Rajdhani:wght@600;700', slug: 'rajdhani' },
];

/**
 * Identify the subset from its unicode-range. The `/* latin *\/` comments cannot be
 * used: splitting on "@font-face" leaves each comment attached to the previous block.
 */
function subsetOf(range = '') {
  if (range.startsWith('U+0000-00FF')) return 'latin';
  // Must be the full latin-ext range: Vietnamese also opens at U+0102.
  if (range.startsWith('U+0100-02BA')) return 'latin-ext';
  return null; // cyrillic, greek, vietnamese — not needed here
}

await mkdir(OUT, { recursive: true });

const faces = [];

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Google returns one @font-face block per unicode subset; keep latin only.
  const blocks = css.split('@font-face').slice(1);
  for (const block of blocks) {
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] || 'normal';
    const src = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    if (!src || !weight) continue;

    // Keep latin and latin-ext; unicode-range means the browser only fetches
    // latin-ext when a page actually contains those characters.
    const subset = subsetOf(range);
    if (!subset) continue;

    const file = `${fam.slug}-${weight}-${subset}.woff2`;
    const bin = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(path.join(OUT, file), bin);
    faces.push({ family: fam.name, weight, style, file, range, bytes: bin.length });
    console.log(`${file.padEnd(28)} ${Math.round(bin.length / 1024)} KB`);
  }
}

// Emit the stylesheet the app imports.
const css = `/* Self-hosted webfonts — generated by scripts/fetch-fonts.mjs, do not edit by hand. */\n\n${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`
  )
  .join('\n\n')}\n`;

await writeFile(path.join(process.cwd(), 'client', 'src', 'styles', 'fonts.css'), css);
console.log(`\n${faces.length} faces -> client/src/styles/fonts.css`);
